// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thoughts.DAL;

#nullable disable

namespace Thoughts.DAL.SqlServer.Migrations.FileStorageDbMigrations
{
    [DbContext(typeof(FileStorageDb))]
    [Migration("20221011171334_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Thoughts.DAL.Entities.UploadedFile", b =>
                {
                    b.Property<string>("Sha1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("Access")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileNameForFileStorage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Flags")
                        .HasColumnType("tinyint");

                    b.Property<string>("Md5")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Meta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameForDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sha1");

                    b.HasIndex("Md5", "Meta", "Sha1")
                        .IsUnique()
                        .HasFilter("[Md5] IS NOT NULL AND [Meta] IS NOT NULL");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
